# Generated by Django 5.1.3 on 2024-11-18 10:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('created_datedate', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='clients/')),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('occupé', 'Occupé'), ('disponible', 'Disponible'), ('endommagé', 'Endommagé')], default='disponible', max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='equipement/')),
                ('occupied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.client')),
            ],
        ),
        migrations.DeleteModel(
            name='Billet',
        ),
    ]
