# Generated by Django 5.1.3 on 2024-11-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_client_equipement_delete_billet'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adresse',
            field=models.CharField(default='Inconnu', max_length=100),
        ),
    ]
