# Generated by Django 5.1.3 on 2024-11-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_client_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='image',
            field=models.ImageField(upload_to='equipements/'),
        ),
    ]
