# Generated by Django 5.1.3 on 2024-11-18 19:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_client_equipement_emprunté'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='equipement_emprunté',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='occupied_by',
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_retour_prevue', models.DateTimeField()),
                ('date_retour_effective', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='blog.client')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='blog.equipement')),
            ],
            options={
                'unique_together': {('equipement', 'date_emprunt')},
            },
        ),
        migrations.AddField(
            model_name='equipement',
            name='emprunteurs',
            field=models.ManyToManyField(related_name='equipements_empruntes', through='blog.Emprunt', to='blog.client'),
        ),
    ]
